openapi: 3.2.0
info:
  title: Sumo Logic Span Analytics API
  description: '# Getting Started

    Welcome to the Sumo Logic API reference.'
  version: 1.0.0
  x-logo:
    url: ./sumologic_logo.png
servers:
- url: https://api.au.sumologic.com/api/
  description: AU deployment API server
- url: https://api.ca.sumologic.com/api/
  description: CA deployment API server
- url: https://api.de.sumologic.com/api/
  description: DE deployment API server
- url: https://api.eu.sumologic.com/api/
  description: EU deployment API server
- url: https://api.fed.sumologic.com/api/
  description: FED deployment API server
- url: https://api.jp.sumologic.com/api/
  description: JP deployment API server
- url: https://api.kr.sumologic.com/api/
  description: KR deployment API server
- url: https://api.in.sumologic.com/api/
  description: IN deployment API server
- url: https://api.sumologic.com/api/
  description: US1 deployment API server
- url: https://api.us2.sumologic.com/api/
  description: US2 deployment API server
security:
- basicAuth: []
tags:
- name: spanAnalytics
  description: 'Span Analytics API


    The Span Analytics API allows you to browse spans collected in the system. You can execute queries to find individual spans matching provided search criteria as well as run aggregated span queries and retrieve their results. For more information, see Spans.'
  x-displayName: Span Analytics
paths:
  /v1/tracing/spanquery:
    post:
      tags:
      - spanAnalytics
      summary: Run A Span Analytics Query Asynchronously
      description: Execute a span analytics query and get the id to fetch its status and results. Use the Span Query Status endpoint to check a query status. When the query has been completed, use the Span Query Result endpoint to get the result of the asynchronous query.
      operationId: createSpanQuery
      parameters: []
      requestBody:
        description: Query parameters.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpanQueryRequest'
        required: true
      responses:
        '200':
          description: Query execution result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpanQueryResponse'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/tracing/spanquery/{queryId}:
    delete:
      tags:
      - spanAnalytics
      summary: Cancel A Span Analytics Query
      description: Cancel a currently processed span search query with the given id.
      operationId: cancelSpanQuery
      parameters:
      - name: queryId
        in: path
        description: Identifier of the query to cancel.
        required: true
        schema:
          type: string
          example: 195038749d21ad109242c95cbbc8709d
      responses:
        '204':
          description: Query canceled successfully.
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/tracing/spanquery/{queryId}/status:
    get:
      tags:
      - spanAnalytics
      summary: Get A Span Analytics Query Status
      description: Get a status of a span analytics query with the given id. When the query has been completed, use the Span Query Result endpoint to get the result of the asynchronous query.
      operationId: getSpanQueryStatus
      parameters:
      - name: queryId
        in: path
        description: Identifier of the executed query.
        required: true
        schema:
          type: string
          example: 195038749d21ad109242c95cbbc8709d
      responses:
        '200':
          description: Details about the given span query.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpanQueryStatusResponse'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/tracing/spanquery/{queryId}/pause:
    put:
      tags:
      - spanAnalytics
      summary: Pause A Span Analytics Query
      description: Pause a currently processed span search query with the given id.
      operationId: pauseSpanQuery
      parameters:
      - name: queryId
        in: path
        description: Identifier of the query to pause.
        required: true
        schema:
          type: string
          example: 195038749d21ad109242c95cbbc8709d
      responses:
        '204':
          description: Query paused successfully.
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/tracing/spanquery/{queryId}/resume:
    put:
      tags:
      - spanAnalytics
      summary: Resume A Span Analytics Query
      description: Resume a previously paused span search query with the given id.
      operationId: resumeSpanQuery
      parameters:
      - name: queryId
        in: path
        description: Identifier of the query to resume.
        required: true
        schema:
          type: string
          example: 195038749d21ad109242c95cbbc8709d
      responses:
        '204':
          description: Query resumed successfully.
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/tracing/spanquery/{queryId}/rows/{rowId}/spans:
    get:
      tags:
      - spanAnalytics
      summary: Get Results Of A Span Analytics Query
      description: Get a list of spans matching a query with the specified id. The response is paginated with a default limit of 100 spans per page.
      operationId: getSpanQueryResult
      parameters:
      - name: queryId
        in: path
        description: Identifier of the executed query.
        required: true
        schema:
          type: string
          example: 195038749d21ad109242c95cbbc8709d
      - name: rowId
        in: path
        description: Identifier of the query row.
        required: true
        schema:
          type: string
          example: A
      - name: limit
        in: query
        description: Limit of the number of spans returned in the response.
        required: false
        schema:
          maximum: 500
          minimum: 1
          type: integer
          format: int32
          example: 100
          default: 100
      - name: token
        in: query
        description: Continuation token to get the next page of results. A page object with the next continuation token is returned in the response body. Subsequent GET requests should specify the continuation token to get the next page of results. `token` is set to null when no more pages are left.
        required: false
        schema:
          type: string
          example: dlFXd0lhSkxzRjAwYnpVZkMrRmlhYnF4cGtNMWdnVEI
      responses:
        '200':
          description: Details about the given span query.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpanQueryResultSpansResponse'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/tracing/spanquery/{queryId}/rows/{rowId}/facets:
    get:
      tags:
      - spanAnalytics
      summary: Get A List Of Facets Of A Span Analytics Query
      description: Get a list of facets of a span analytics query with the specified id.
      operationId: getSpanQueryFacets
      parameters:
      - name: queryId
        in: path
        description: Identifier of the executed query.
        required: true
        schema:
          type: string
          example: 195038749d21ad109242c95cbbc8709d
      - name: rowId
        in: path
        description: Identifier of the query row.
        required: true
        schema:
          type: string
          example: A
      responses:
        '200':
          description: The list of facets from the executed query.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpanQueryResultFacetsResponse'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/tracing/spanquery/{queryId}/aggregates:
    get:
      tags:
      - spanAnalytics
      summary: Get Span Analytics Query Aggregated Results
      description: Get span aggregation results for an aggregated span analytics query with the specified id. Only aggregated rows being part of the executed query will have matching results in the response of this endpoint.
      operationId: getSpanQueryAggregates
      parameters:
      - name: queryId
        in: path
        description: Identifier of the executed query.
        required: true
        schema:
          type: string
          example: 195038749d21ad109242c95cbbc8709d
      responses:
        '200':
          description: The aggregation result of the executed query.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpanQueryAggregateResponse'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/tracing/spanquery/fields:
    get:
      tags:
      - spanAnalytics
      summary: Get Filter Fields For Span Analytics Queries
      description: Get a list of available fields which can be used in span analytics queries.
      operationId: getSpanQueryFields
      parameters: []
      responses:
        '200':
          description: List of available fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpanQueryFieldsResponse'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/tracing/spanquery/fields/{field}/values:
    get:
      tags:
      - spanAnalytics
      summary: Get Span Analytics Query Filter Field Values
      description: Get a list of available values for the given span analytics query filter field. Not all fields support value listing. The response is paginated with a default limit of 10 field values per page.
      operationId: getSpanQueryFieldValues
      parameters:
      - name: field
        in: path
        description: Field identifier.
        required: true
        schema:
          type: string
      - name: query
        in: query
        description: Search filter to apply on the values to be returned. Only values containing the search query term will be returned.
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: The maximum number of results to fetch.
        required: false
        schema:
          maximum: 500
          minimum: 1
          type: integer
          format: int32
          default: 10
      - name: token
        in: query
        description: Continuation token to get the next page of results. A page object with the next continuation token is returned in the response body. Subsequent GET requests should specify the continuation token to get the next page of results. `token` is set to null when no more pages are left.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: List of available filter values for the given field.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceFieldValuesResponse'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      required:
      - errors
      - id
      type: object
      properties:
        id:
          type: string
          description: An identifier for the error; this is unique to the specific API request.
          example: IUUQI-DGH5I-TJ045
        errors:
          type: array
          description: A list of one or more causes of the error.
          example:
          - code: auth:password_too_short
            message: Your password was too short.
          - code: auth:password_character_classes
            message: Your password did not contain any non-alphanumeric characters
          items:
            $ref: '#/components/schemas/ErrorDescription'
    SpanQueryResultSpansResponse:
      required:
      - spanPage
      type: object
      properties:
        spanPage:
          type: array
          description: List of trace spans.
          items:
            $ref: '#/components/schemas/SpanQuerySpanData'
        next:
          type: string
          description: Next continuation token.
          example: Mi93V0ZqTTBzaW89
    TraceFieldValuesResponse:
      required:
      - fieldValues
      - totalCount
      type: object
      properties:
        fieldValues:
          type: array
          description: List of filter field values.
          items:
            type: string
        totalCount:
          type: integer
          description: Total number of values for a field matching the query. Can be approximated when it's above 3000.
          format: int64
          example: 1234
        next:
          type: string
          description: Next continuation token.
          example: Mi93V0ZqTTBzaW89
    TraceSpanStatus:
      required:
      - code
      type: object
      properties:
        code:
          type: string
          description: 'Status code of the span. Possible values: `OK`, `ERROR`, `UNKNOWN`.'
          example: OK
        message:
          type: string
          description: Optional descriptive message about the status, could be an http status code or the kind of an error, e.g. OSError.
          example: '404'
    SpanQueryRow:
      required:
      - queryString
      - rowId
      type: object
      properties:
        queryString:
          type: string
          description: Query string using the log search syntax.
        rowId:
          pattern: ^[a-zA-Z0-9_]*$
          type: string
          description: An identifier used to reference this particular row of the query request. Within a query, row ids must have distinct values.
          example: A
    TimeRangeBoundary:
      required:
      - type
      type: object
      properties:
        type:
          type: string
          description: 'Type of the time range boundary. Value must be from list: - `RelativeTimeRangeBoundary`, - `EpochTimeRangeBoundary`, - `Iso8601TimeRangeBoundary`, - `LiteralTimeRangeBoundary`.'
          example: RelativeTimeRangeBoundary
      discriminator:
        propertyName: type
    SpanQueryAggregateMetaData:
      required:
      - data
      type: object
      properties:
        data:
          maxProperties: 1000
          type: object
          additionalProperties:
            type: string
          description: The value of the metadata.
          example:
            deployment: dev
            cluster: frontend
            instance: frontend-12
          default: {}
    SpanQueryRowError:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          description: The error code.
          example: spanquery:query_validation_error
        message:
          type: string
          description: Short description of the occured error.
          example: Query A was invalid
        details:
          type: string
          description: Details about the occured error.
          example: '[1.78] failure: ''('' expected but '')'' found.'
    SpanQuerySpanData:
      required:
      - duration
      - startedAt
      type: object
      properties:
        spanId:
          type: string
          description: Identifier of the span.
          example: 00000000002317A9
        traceId:
          type: string
          description: Identifier of the trace.
          example: 1BB004A0005213C2
        parentSpanId:
          type: string
          description: Identifier of the parent span, if any. If the span has no parent it's considered a root span.
          example: 000000000003C7BE
        operationName:
          type: string
          description: The name of the operation given to the span.
          example: retrieveAccount
        service:
          type: string
          description: The name of the service this span is part of.
          example: user-service
        remoteService:
          type: string
          description: Name of the possible remote span's service.
          example: external-service
        duration:
          type: integer
          description: Number of nanoseconds the span lasted.
          format: int64
          example: 212957153
        startedAt:
          type: string
          description: Date and time the span was started in [ISO 8601 / RFC3339](https://tools.ietf.org/html/rfc3339) format.
          format: date-time
          example: 2019-11-22 09:00:00+00:00
        status:
          $ref: '#/components/schemas/TraceSpanStatus'
        kind:
          pattern: ^(CLIENT|SERVER|PRODUCER|CONSUMER|INTERNAL)$
          type: string
          description: 'Span kind describes the relationship between the Span, its parents, and its children in a Trace. Possible values: `CLIENT`, `SERVER`, `PRODUCER`, `CONSUMER`, `INTERNAL`.'
          example: SERVER
          x-pattern-message: Should be either `CLIENT`, `SERVER`, `PRODUCER`, `CONSUMER` or `INTERNAL`.
        tagsJSON:
          type: string
          description: Tags attached to this span as JSON.
          example: "{\n  &quot;http.host&quot;:&quot;http://example.com&quot;,\n  &quot;http.request.method&quot;:&quot;GET&quot;\n}"
        metadata:
          maxProperties: 1000
          type: object
          additionalProperties:
            type: string
          description: Metadata attached to the span.
          example:
            _sourceCategory: account-backend
    SpanQueryAggregateAggregateData:
      required:
      - avg
      - latest
      - max
      - min
      - sum
      type: object
      properties:
        max:
          type: number
          description: The maximum value in the series.
          format: double
          example: 10.0
        min:
          type: number
          description: The minimum value in the series.
          format: double
          example: 1.2
        avg:
          type: number
          description: The average value in the series.
          format: double
          example: 5.6
        sum:
          type: number
          description: The sum of all the values in the series.
          format: double
          example: 123.4
        latest:
          type: number
          description: The last value in the series.
          format: double
          example: 23.4
        count:
          type: number
          description: The number of values in the series.
          format: double
          example: 600
    SpanQueryRowFacet:
      required:
      - cardinality
      - dataType
      - name
      type: object
      properties:
        name:
          type: string
          description: Name of the field facet.
          example: _sourceHost
        cardinality:
          type: integer
          description: The number of unique values this field occured.
          format: int32
          example: 3
        dataType:
          pattern: ^(String|Int|Long|Double|Boolean)$
          type: string
          description: Data type of the field.
          example: String
          x-pattern-message: Should be either `String`, `Int`, `Long`, `Double` or `Boolean`.
        inSchema:
          type: boolean
          description: Indicates whether the field is available in the span schema.
          example: false
        valueFrequency:
          maxProperties: 1000
          type: object
          additionalProperties:
            type: integer
            format: int64
          description: Map of field value frequencies.
          example:
            _sourceHost: 34099
    NoTraceFieldValuesReason:
      required:
      - code
      - message
      type: object
      properties:
        code:
          pattern: ^(HighCardinalityField|AutocompleteDisabled)$
          type: string
          description: 'A code uniquely identifying the reason for the lack of trace field values. Possible values: `HighCardinalityField`, `AutocompleteDisabled`.'
          example: HighCardinalityField
          x-pattern-message: Should be either `HighCardinalityField`, `AutocompleteDisabled`.
        message:
          type: string
          description: A short English-language description of the reason.
          example: Autocomplete has been disabled for this field due to high cardinality.
    SpanQueryResultFacetsResponse:
      required:
      - facets
      type: object
      properties:
        facets:
          type: array
          description: List of facets.
          items:
            $ref: '#/components/schemas/SpanQueryRowFacet'
    SpanQueryRowResponse:
      required:
      - isAggregation
      - rowId
      type: object
      properties:
        rowId:
          type: string
          description: A unique identifier of the query.
          example: A
        errors:
          type: array
          description: List of errors which occured when executing the query
          items:
            $ref: '#/components/schemas/SpanQueryRowError'
        isAggregation:
          type: boolean
          description: Indicates whether this query is an aggregation
          example: true
          default: false
        executedQuery:
          type: string
          description: The executed query after rewriting
          example: _index=_trace_spans traceId=00000000002317A9
    SpanQueryFieldsResponse:
      required:
      - fields
      type: object
      properties:
        fields:
          type: array
          description: List of span fields.
          items:
            $ref: '#/components/schemas/SpanQueryFieldDetail'
    SpanQueryRequest:
      required:
      - queryRows
      - timeRange
      type: object
      properties:
        queryRows:
          type: array
          description: A list of span analytics queries.
          items:
            $ref: '#/components/schemas/SpanQueryRow'
        timeRange:
          $ref: '#/components/schemas/ResolvableTimeRange'
        timeZone:
          type: string
          description: Time zone for the query time ranges. Follow the format in the [IANA Time Zone Database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
          example: America/Los_Angeles
          default: UTC
    TraceFieldDetail:
      required:
      - field
      - fieldType
      - type
      type: object
      properties:
        field:
          type: string
          description: Filter field name.
          example: operation
        fieldType:
          pattern: ^(SpanAttribute|SpanEventAttribute)$
          type: string
          description: 'Indicates the kind of a field. Possible values: `SpanAttribute`, `SpanEventAttribute`.'
          example: SpanEventAttribute
          default: SpanAttribute
          x-pattern-message: 'Should be one of: `SpanAttribute`, `SpanEventAttribute`.'
        valueListing:
          type: boolean
          description: Indicates whether values for this field can be listed.
          example: false
        description:
          type: string
          description: Short description of the field.
          example: A piece of the workflow represented by a span
        type:
          type: string
          description: 'The type the values of this field will have. Possible values: `DoubleTracingValue`, `IntegerTracingValue`, `StringTracingValue`, `DateTimeTracingValue`.'
          example: StringTracingValue
        noValuesReason:
          $ref: '#/components/schemas/NoTraceFieldValuesReason'
    ResolvableTimeRange:
      required:
      - type
      type: object
      properties:
        type:
          type: string
          description: Type of the time range. Value must be either `CompleteLiteralTimeRange` or `BeginBoundedTimeRange`.
      example:
        type: BeginBoundedTimeRange
        from:
          type: RelativeTimeRangeBoundary
          relativeTime: -15m
      discriminator:
        propertyName: type
    ErrorDescription:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          description: An error code describing the type of error.
          example: auth:password_too_short
        message:
          type: string
          description: A short English-language description of the error.
          example: Your password was too short.
        detail:
          type: string
          description: An optional fuller English-language description of the error.
          example: Your password was 5 characters long, the minimum length is 12 characters. See http://example.com/password for more information.
        meta:
          type: object
          description: An optional list of metadata about the error.
          example:
            minLength: 12
            actualLength: 5
    SpanQueryRowStatus:
      required:
      - count
      - rowId
      - status
      type: object
      properties:
        rowId:
          type: string
          description: A unique identifier of the query.
          example: A
        status:
          pattern: ^(Processing|Finished|Error|Paused)$
          type: string
          description: 'Status of the query. Possible values: `Processing`, `Finished`, `Error`, `Paused`.'
          example: Processing
          x-pattern-message: Should be either `Processing`, `Finished`, `Error`, `Paused`.
        statusMessage:
          type: string
          description: Descriptive message of the status.
          example: Finished successfully
        count:
          minimum: 0
          type: integer
          description: Number of results matching the query
          format: int64
          example: 3215
        approximatedFieldCounts:
          type: boolean
          description: Indicates whether facet field cardinality counts are approximated or not.
          example: false
        facetsCompleted:
          type: boolean
          description: Indicates whether facets calculation has completed.
          example: false
    SpanQueryAggregatePointData:
      required:
      - y
      type: object
      properties:
        x:
          type: number
          description: Value that represents a point on the x axis.
          format: double
          example: 1.0
        y:
          type: string
          description: Value that represents a point on the y axis.
          example: '12.3'
        xAxisValues:
          maxProperties: 1000
          type: object
          additionalProperties:
            type: string
          description: Values that represents a point on the x axis.
          example:
            operation: /get/accounts
            service: accountService
          default: {}
    BeginBoundedTimeRange:
      allOf:
      - $ref: '#/components/schemas/ResolvableTimeRange'
      - required:
        - from
        type: object
        properties:
          from:
            $ref: '#/components/schemas/TimeRangeBoundary'
          to:
            $ref: '#/components/schemas/TimeRangeBoundary'
    SpanQueryResponse:
      required:
      - queryId
      - queryRows
      type: object
      properties:
        queryId:
          type: string
          description: Id of the created query
        queryRows:
          type: array
          description: A list of row responses with details about individual queries.
          items:
            $ref: '#/components/schemas/SpanQueryRowResponse'
        hasErrors:
          type: boolean
          description: Indicates whether there was an error while executing the query.
          example: true
          default: false
        timeRange:
          $ref: '#/components/schemas/BeginBoundedTimeRange'
    SpanQueryAggregateResult:
      required:
      - series
      - status
      type: object
      properties:
        status:
          pattern: ^(Processing|Finished|Error|Paused)$
          type: string
          description: 'Status of the query. Possible values: `Processing`, `Finished`, `Error`, `Paused`.'
          example: Processing
          x-pattern-message: Should be either `Processing`, `Finished`, `Error`, `Paused`.
        statusMessage:
          type: string
          description: Descriptive message of the status
          example: Finished successfully
        series:
          type: array
          description: The series returned from a search.
          items:
            $ref: '#/components/schemas/SpanQueryAggregateDataSeries'
    SpanQueryAggregateResponse:
      required:
      - result
      type: object
      properties:
        result:
          $ref: '#/components/schemas/SpanQueryAggregateResult'
    SpanQueryFieldDetail:
      allOf:
      - $ref: '#/components/schemas/TraceFieldDetail'
      - required:
        - inSchema
        type: object
        properties:
          inSchema:
            type: boolean
            description: Indicates whether the field is available in the schema.
            example: false
    SpanQueryAggregateDataSeries:
      required:
      - dataPoints
      - name
      - queryId
      type: object
      properties:
        queryId:
          type: string
          description: The id of the query.
          example: A
        name:
          type: string
          description: "The meaning of 'name' depends on the series type.\n  - For results of type 'timeseries', it is the value of the x axis 'field' key.\n  - For results of type 'nontimeseries', it is the name of one of the fields that is not part of 'xAxisKeys'.\n  - For results of type 'table', it is the comma-separated string of names of all fields.\n"
          example: max(Disk_Used)
        dataPoints:
          type: array
          description: A list of data points in the series.
          items:
            $ref: '#/components/schemas/SpanQueryAggregatePointData'
        aggregateInfo:
          $ref: '#/components/schemas/SpanQueryAggregateAggregateData'
        metaData:
          $ref: '#/components/schemas/SpanQueryAggregateMetaData'
        seriesType:
          pattern: ^(TIMESERIES|NONTIMESERIES|TABLE)$
          type: string
          description: Type of the visual series.
          example: TIMESERIES
          x-pattern-message: Should be either `TIMESERIES`, `NONTIMESERIES`, `TABLE`.
        xAxisKeys:
          type: array
          description: Keys that will be plotted as a point on the x axis.
          example:
          - _sourceCategory
          - _sourceHost
          items:
            type: string
        valueType:
          pattern: ^(STRING|DOUBLE)$
          type: string
          description: Type of the values in the series.
          example: DOUBLE
          x-pattern-message: Should be either `STRING`, `DOUBLE`.
    SpanQueryStatusResponse:
      required:
      - queryRows
      - status
      type: object
      properties:
        queryRows:
          type: array
          description: A list of span analytics queries.
          items:
            $ref: '#/components/schemas/SpanQueryRowStatus'
        status:
          pattern: ^(Processing|Finished|Error|Paused)$
          type: string
          description: 'Status of the query. Possible values: `Processing`, `Finished`, `Error`, `Paused`'
          example: Processing
          x-pattern-message: Should be either `Processing`, `Finished`, `Error`, `Paused`.
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
x-tagGroups:
- name: Archive Management
  tags:
  - archiveManagement
- name: Health Events
  tags:
  - healthEvents
- name: Infrequent Data Tier
  tags:
  - logSearchesEstimatedUsage
- name: Ingest Budgets Management V2
  tags:
  - ingestBudgetManagementV2
- name: Library Management
  tags:
  - appManagement
  - appManagementV2
  - contentManagement
  - dashboardManagement
  - folderManagement
  - lookupManagement
  - contentPermissions
  - logSearchesManagement
  - parsersLibraryManagement
- name: Metrics
  tags:
  - metricsSearchesManagement
  - transformationRuleManagement
  - metricsQuery
  - metricsSearchesManagementV2
- name: Security Management
  tags:
  - accessKeyManagement
  - oauthManagement
  - accountManagement
  - passwordPolicy
  - policiesManagement
  - samlConfigurationManagement
  - serviceAllowlistManagement
  - serviceAccountManagement
  - scimUserManagement
- name: Organizations Management
  tags:
  - orgsManagement
- name: Settings Management
  tags:
  - connectionManagement
  - dynamicParsingRuleManagement
  - extractionRuleManagement
  - fieldManagementV1
  - partitionManagement
  - scheduledViewManagement
  - logsDataForwardingManagement
  - dataDeletionRules
- name: Tokens Management
  tags:
  - tokensLibraryManagement
- name: Tracing
  tags:
  - traces
  - spanAnalytics
  - serviceMap
- name: Users and Roles Management
  tags:
  - roleManagement
  - roleManagementV2
  - userManagement
- name: Threat Intel Ingest Management
  tags:
  - threatIntelIngest
  - threatIntelIngestProducer
- name: OpenTelemetry Collector Management
  tags:
  - otCollectorManagementExternal
- name: Source Template Management
  tags:
  - sourceTemplateManagementExternal
- name: Schema Base Management
  tags:
  - schemaBaseManagement
- name: Event Analytics Management
  tags:
  - eventAnalytics
- name: Budget Management
  tags:
  - budgetManagement
- name: Macro Management
  tags:
  - macroManagement
- name: Muting Schedules Management
  tags:
  - mutingSchedulesLibraryManagement
- name: SLO Management
  tags:
  - slosLibraryManagement
- name: Monitor Management
  tags:
  - monitorsLibraryManagement
